# Generated by Django 4.2.5 on 2024-03-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0002_laptimehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LapTimeHistory',
        ),
    ]
