# Generated by Django 4.2.5 on 2024-03-02 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0003_delete_laptimehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.DurationField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaceApp.userprofile')),
            ],
        ),
    ]
