# Generated by Django 4.2.5 on 2024-03-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
