# Generated by Django 4.2.5 on 2024-03-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0016_companypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyPayment',
        ),
    ]
