# Generated by Django 4.2.5 on 2024-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0018_companypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyPayment',
        ),
    ]
