# Generated by Django 4.2.5 on 2024-03-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0020_companypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypayment',
            name='razorpay_payment_id',
        ),
    ]
