# Generated by Django 4.2.5 on 2024-03-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0021_remove_companypayment_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='past_lap_times',
            field=models.TextField(blank=True, null=True),
        ),
    ]
